### ISSUE TITLE
Issue with regenerating results in trading_margin_a2c.py

### ISSUE THREAD

**Issue by alifazaeli96** [JingyiGu/Margin-Trader#3]
I am having trouble generating the expected results using the trading_margin_a2c.py script. When I run the script, I get the following output:
Annual return         -0.283977
Cumulative returns    -0.357725
Annual volatility      0.251660
Sharpe ratio          -1.200733
Calmar ratio          -0.679167
Stability              0.317685
Max drawdown          -0.418125
Omega ratio            0.764102
Sortino ratio         -1.412423
Skew                        NaN
Kurtosis                    NaN
Tail ratio             0.731687
Daily value at risk   -0.032905
dtype: float64
[*********************100%%**********************]  1 of 1 completed
Shape of DataFrame:  (334, 8)
==============Compare to DJIA===========
hit end!
Annual return         -0.033163
Cumulative returns    -0.095863
Annual volatility      0.226954
Sharpe ratio          -0.035414
Calmar ratio          -0.078212
Stability              0.446307
Max drawdown          -0.424017
Omega ratio            0.994021
Sortino ratio         -0.049710
Skew                        NaN
Kurtosis                    NaN
Tail ratio             0.913350
Daily value at risk   -0.028625
dtype: float64
[*********************100%%**********************]  1 of 1 completed
Shape of DataFrame:  (754, 8)
==============Compare to DJIA===========
Annual return          0.128900
Cumulative returns     0.437304
Annual volatility      0.172500
Sharpe ratio           0.790368
Calmar ratio           0.587491
Stability              0.337695
Max drawdown          -0.219408
Omega ratio            1.144252
Sortino ratio          1.117012
Skew                        NaN
Kurtosis                    NaN
Tail ratio             1.018332
Daily value at risk   -0.021192
dtype: float64

Process finished with exit code 0

Steps to Reproduce:

   dl trading_margin_main.zip
    Run trading_margin_a2c.py with the provided configuration.
    Observe the results.

Environment:
    
    Python version: [3.10]
    Relevant libraries and versions
![profit_trade](https://github.com/JingyiGu/Margin-Trader/assets/122299208/1d531a2e-de07-45e7-a900-4f6f4ccbb582)
![profit_test](https://github.com/JingyiGu/Margin-Trader/assets/122299208/4e09d803-747b-4ec7-a64a-ddd144ec600d)
[perf_stats_trade.csv](https://github.com/user-attachments/files/16097163/perf_stats_trade.csv)

Expected Behavior:

I expected the script to generate results that align more closely with those reported in the original paper.
Actual Behavior:

The script generates results with significant discrepancies, particularly in terms of the annual return and Sharpe ratio.
[perf_stats_test.csv](https://github.com/user-attachments/files/16097164/perf_stats_test.csv)

**Comment by JingyiGu** [comment]
The code gives an example of implementation. The optimal performance of RL models usually relies on the value of hyper parameters, our paper provides the tuning range and please refer to it for tuning. The trained model is also uploaded and can be loaded to run directly.

**Comment by raulikeda** [comment]
I tried to load the trained model in repository, but the observation size is not matching. The actual observation size in the MarginTradingEnv is 296 (which I assume it is 6 + n + n + 8n for 29 of 30 stocks - we have a problem with DOW, which is expelled in the preprocessing). But the model is expecting 276. Was the model trained with 27 stocks or there is something else I am not considering?

**Comment by JingyiGu** [comment]
(1) The environment was updated in April. The trained model aligns with the previous version on 11/2023. Please follow the previous version.
(2) Tickers in DJI have been changed during this period and hence the number has increased. You may find DJI tickers at that time to match the observations.
