### ISSUE TITLE
Sharpe ratio

### ISSUE THREAD

**Issue by alifazaeli96** [JingyiGu/Margin-Trader#4]
Hello,

Thank you for the help with my previous issue!

I’m currently using the margin trader and noticed that the Sharpe Ratio calculation doesn’t seem to match the standard financial formula. Specifically, I expected the Sharpe Ratio to be calculated as:

Sharpe Ratio = (Mean of Returns - Risk-Free Rate) / Standard Deviation of Returns

However, the results I’m seeing in the library output appear to differ. For example, in the A2C long and short , a calculation of 18.5 / 25.6 would yield approximately 0.72, not 0.793. If we consider a positive risk-free rate, the Sharpe Ratio should be even lower than 0.72.

Could you clarify how the Sharpe Ratio is being calculated in FinRL? Is there an adjustment or specific methodology applied?

Understanding this would really help me interpret the performance metrics for my portfolio optimization project.

Thank you very much for your assistance!

Best regards,
Ali Fazaeli

[1707.06347v2.pdf](https://github.com/user-attachments/files/17558368/1707.06347v2.pdf)

**Comment by JingyiGu** [comment]
When I implement this function, FinRL uses pyfolio library to calculate metric. For the detailed calculation, please refer to source code of FinRL and pyfolio.
